### ISSUE TITLE
Question about initial conditions of Blindfolded tricks #1

### ISSUE THREAD

**Issue by clintonblackmore** [sharkdp/great-puzzles#3]
Very interesting.  If you can put puzzles up on github, I suppose issues can be filed against them (and I assume that anyone reading would expect spoilers).

In the first Blindfolded tricks puzzle:

> [You are blindfolded and] There is a deck of 52 cards on the table in front of you. Ten of them are face-up and the rest are face-down. Split the deck such that each new stack has an equal number of face-up cards.

It is not at all clear to me how the cards are laid out (which makes it difficult to permute them, mentally, in order to solve the problem.)  Is there one stack of cards?  Are there two, with different numbers of cards?  Are they, perhaps, splayed all across the table?

On a close re-reading of the answer, it would seem they are all in one stack to begin with, and, also from the answer, I'm assuming that the ten face-up cards are shuffled amongst the face-down cards.

Maybe I don't play with cards enough ...

**Comment by pickten** [comment]
It doesn't matter. The reader is assumed to be dextrous enough to know where the cards are, even if the reader doesn't know whether they are face up or face down. Thus, regardless of how they arranged, the reader can put them in any arrangement, so the reader could start out by stacking them if they were dispersed, or dispersing them if they were stacked. As you mention, the face up cards are shuffled in with the others.

**Comment by clintonblackmore** [comment]
Oh, I hadn't considered that all the cards could be coalesced into one stack, making the initial arrangement irrelevant (so long as you could do it without flipping any of the cards).

**Comment by sharkdp** [comment]
> Very interesting. If you can put puzzles up on github, I suppose issues can be filed against them

:+1: 

> Thus, regardless of how they arranged, the reader can put them in any arrangement, so the reader could start out by stacking them if they were dispersed, or dispersing them if they were stacked.

Yes, thanks for the clarification. Would it be better to explain the puzzle as "There is a _stack_ of 52 cards on the table in front of you" (instead of deck)? The ambiguity doesn't really add much value..
